# Generated by Django 4.0 on 2021-12-23 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santabot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователя'},
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название игры')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('cost_range', models.TextField(blank=True, verbose_name='Ценовой диапозон')),
                ('last_register_date', models.DateTimeField(verbose_name='Последний день регистрации')),
                ('sending_date', models.DateTimeField(verbose_name='Дата отправки подарка')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santabot.user', verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
            },
        ),
    ]
