# Generated by Django 4.0 on 2021-12-24 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santabot', '0003_alter_event_last_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='last_register_date',
            field=models.DateTimeField(verbose_name='Последний день регистрации'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sending_date',
            field=models.DateTimeField(verbose_name='Дата отправки подарка'),
        ),
    ]
