# Generated by Django 4.0 on 2021-12-25 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('santabot', '0004_alter_event_last_register_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='external_id',
            field=models.PositiveIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(verbose_name='Имя'),
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(verbose_name='Номер телефона')),
                ('letter_for_santa', models.TextField(blank=True, verbose_name='Письмо Санте')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santabot.event', verbose_name='Игра')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santabot.user', verbose_name='Имя участника')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.TextField(verbose_name='Интерес')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='santabot.participant', verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Интерес',
                'verbose_name_plural': 'Интересы',
            },
        ),
    ]
