# Generated by Django 4.0 on 2021-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santabot', '0006_remove_interests_participant_participant_interests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='interest',
            field=models.CharField(max_length=30, unique=True, verbose_name='Интерес'),
        ),
    ]
