# Generated by Django 4.0 on 2021-12-27 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('santabot', '0008_participant_name_alter_participant_user_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Имя участника'),
        ),
    ]
